b:
	docker compose up -d
	docker logs --follow ministry
build:
	docker compose up -d
	docker logs --follow ministry

c:
	docker compose down
clean:
	docker compose down

s:
	docker container restart ministry && docker logs --follow ministry
start:
	docker container restart ministry && docker logs --follow ministry